Updated codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -6,49 +6,49 @@ workflows:
         name: React Native Android
         scripts:
             - echo "Hello World!"
-        # max_build_duration: 120
-        # instance_type: mac_mini_m2
-        # environment:
-        #   android_signing:
-        #     - keystore_reference
-        #   groups:
-        #     - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
-        #   vars:
-        #     PACKAGE_NAME: "io.codemagic.sample.reactnative" # <-- Put your package name here e.g. com.domain.myapp
-        #   node: v19.7.0
-        # scripts:
-        #     - name: Install npm dependencies
-        #       script: |
-        #         npm install
-        #     - name: Set Android SDK location
-        #       script: |
-        #         echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"            
-        #     - name: Build Android release
-        #       script: |
-        #         LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-        #         if [ -z LATEST_BUILD_NUMBER ]; then
-        #           # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
-        #           UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-        #         else
-        #           UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-        #         fi
-        #         cd android
-        #         ./gradlew bundleRelease \
-        #           -PversionCode=$UPDATED_BUILD_NUMBER \
-        #           -PversionName=1.0.$UPDATED_BUILD_NUMBER
-        # artifacts:
-        #     - android/app/build/outputs/**/*.aab
-        # publishing:
-        #   email:
-        #     recipients:
-        #       - ldeepak@netapp.com
-        #       - amarjees@netapp.com
-        #     notify:
-        #       success: true     # To not receive a notification when a build succeeds
-        #       failure: true    # To not receive a notification when a build fails
-        #   google_play:
-        #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-        #     track: alpha   # Any default or custom track that is not in ‘draft’ status
+        max_build_duration: 120
+        instance_type: mac_mini_m2
+        environment:
+          android_signing:
+            - Keystore
+          groups:
+            - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
+          vars:
+            PACKAGE_NAME: "com.awesomeproject" # <-- Put your package name here e.g. com.domain.myapp
+          node: v19.7.0
+        scripts:
+            - name: Install npm dependencies
+              script: |
+                npm install
+            - name: Set Android SDK location
+              script: |
+                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"            
+            - name: Build Android release
+              script: |
+                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+                if [ -z LATEST_BUILD_NUMBER ]; then
+                  # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+                  UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+                else
+                  UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                fi
+                cd android
+                ./gradlew bundleRelease \
+                  -PversionCode=$UPDATED_BUILD_NUMBER \
+                  -PversionName=1.0.$UPDATED_BUILD_NUMBER
+        artifacts:
+            - android/app/build/outputs/**/*.aab
+        publishing:
+          email:
+            recipients:
+              - ldeepak@netapp.com
+              - amarjees@netapp.com
+            notify:
+              success: true     # To not receive a notification when a build succeeds
+              failure: true    # To not receive a notification when a build fails
+          # google_play:
+          #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+          #   track: alpha   # Any default or custom track that is not in ‘draft’ status
     react-native-ios:
         name: React Native iOS
         max_build_duration: 120
